import { anthropic } from "@ai-sdk/anthropic";
import { generateText, Output, tool } from "ai";
import { z } from "zod";

import { reviewSubagentPrompt } from "@/lib/prompts/review-subagent";
import { normalizeReviewOutput, ReviewGenerationSchema } from "@/lib/schemas/review";

// The review is generated by a dedicated sub-agent call rather than inline by the
// orchestrator. This separation lets each call have a focused system prompt —
// the orchestrator's prompt is optimized for tool routing, while the sub-agent's
// prompt is optimized for code evaluation. It also means the review output is
// Zod-validated via Output.object, so malformed reviews fail fast rather than
// rendering broken UI.
export const generateStructuredReview = tool({
  description:
    "Generate a structured PR review from gathered context. Call this after collecting sufficient GitHub context.",
  inputSchema: z.object({
    context: z
      .string()
      .describe(
        "Serialized PR context, including diff, file contents, blame history, guidelines, and issues.",
      ),
  }),
  execute: async ({ context }) => {
    const result = await generateText({
      model: anthropic("claude-sonnet-4-6"),
      output: Output.object({ schema: ReviewGenerationSchema }),
      prompt: `Review this pull request using the context below.\n\n${context}`,
      system: reviewSubagentPrompt,
    });

    return normalizeReviewOutput(result.output);
  },
});
